name: kindy
description: "A super app for kindergarten management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.1
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Адаптивность и отзывчивый дизайн
  flutter_screenutil: ^5.9.0   # Адаптивные размеры
  device_preview: ^1.1.0       # Предпросмотр на разных устройствах
  responsive_framework: ^1.1.1 # Отзывчивый фреймворк
  flutter_adaptive_scaffold: ^0.1.8  # Адаптивные макеты
  adaptive_theme: ^3.3.0       # Адаптивные темы
  
  # Локализация
  flutter_localizations:
    sdk: flutter
    
  # UI компоненты
  flutter_staggered_grid_view: ^0.7.0  # Адаптивная сетка
  animations: ^2.0.8                   # Анимации для адаптивного UI
  
  # Утилиты
  flutter_platform_widgets: ^6.1.0     # Платформо-зависимые виджеты
  visibility_detector: ^0.4.0+2        # Определение видимости виджетов
  auto_size_text: ^3.0.0               # Автоматическое изменение размера текста
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  device_frame: ^1.1.0        # Фреймы для разных устройств
  
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # Добавляем шрифты
  fonts:
    - family: Comic Sans MS
      fonts:
        - asset: assets/fonts/Comic Sans MS/Comic Sans MS.ttf
          weight: 400

